- name: Setup installation
  hosts: localhost
  tasks:
    - name: Add plex repo
      kubernetes.core.helm_repository:
        name: plex
        repo_url: "https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages"
    - name: Create the namespace
      kubernetes.core.k8s:
        name: "{{ lookup('env', 'NAMESPACE') }}"
        api_version: v1
        kind: Namespace
        state: present
    - name: Install pv
      vars:
        nfs_server_ip: "{{ lookup('env', 'NFS_SERVER_IP') }}"
        nfs_server_path_plex: "{{ lookup('env', 'NFS_SERVER_PATH_PLEX') }}"
      kubernetes.core.k8s:
        state: present
        template: 'pv.yml'
        namespace: "{{ lookup('env', 'NAMESPACE') }}"  
    - name: Install pvc
      kubernetes.core.k8s:
        state: present
        template: 'pvc.yml'
        namespace: "{{ lookup('env', 'NAMESPACE') }}"  

- name: Install plex
  hosts: localhost
  tasks:
    - name: Apply plex chart
      vars:
        plex_full_hostname: "https://plex.{{ lookup('env', 'DOMAIN_NAME') }}"
        plex_hostname: "plex.{{ lookup('env', 'DOMAIN_NAME') }}"
      kubernetes.core.helm:
        name: "plex"
        chart_ref: plex/plex-media-server
        release_namespace: "{{ lookup('env', 'NAMESPACE') }}"
        state: present
        values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
      tags:
        - install