apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  resources:
    requests:
      storage: 3.5Ti
  volumeName: nfs-plex