apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-media-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: manual
  resources:
    requests:
      storage: 3.5Ti
  volumeName: smb-media
