apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-mc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  resources:
    requests:
      storage: 30Gi
  volumeName: nfs-mc