- name: Uninstall Redis
  hosts: localhost
  tasks:
    - name: Remove bitnami repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"
        state: absent

    - name: Remove redis chart
      kubernetes.core.helm:
        name: "redis-{{ lookup('env', 'NAMESPACE') }}"
        release_namespace: "{{ lookup('env', 'NAMESPACE') }}"
        state: absent
        wait: true